spring:
  application:
    name: attendance-system

application:
  security:
    jwt:
      secret-key: Sp68ckqmBn5sTNAsljOoCmHvS1IRQtesJBWxcOG8iNE=
      expiration: 3600000

user:
  credentials:
    file: src/main/resources/credentials.txt

